### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Ygarr** [KScl/opentyrian2000#11]
Or even ability to launch in wine .

**Comment by KScl** [comment]
It already does--I'm exclusively a Linux user (Mint, to be precise) and have been for the past six years. In fact, the reason there's automatic Windows CI builds is so I don't have to engage with Windows myself, because I hate doing so. I'm just not a fan of doing automatic builds for Linux because I can't predict what versions of libraries are installed on your local machine, and I'd prefer not getting tangled up with AppImages or Flatpaks.

Clone and run `make`, and as long as you have SDL2 and SDL2_net installed, it should work just fine. For Ubuntu-based distros the relevant apt packages are `libsdl2-dev` and `libsdl2-net-dev`.

**Comment by KScl** [comment]
I'd kept this issue open so it would stay visible for others, but it just occurred to me that closing and pinning it instead is a better alternative, so doing that.
