### ISSUE TITLE
Problems when using SDL2 v2.0.14

### ISSUE THREAD

**Issue by ViperAcidZX** [KScl/opentyrian2000#2]
I noticed that the included SDL2.dll file for OpenTyrian2000 is outdated, the one the most recent build on the Releases page is v2.0.12, so I tried to replace it with the most recent version available but I ran into a serious problem with controller inputs where I'm getting some strange ghost inputs that I'm not pressing, making controller support almost impossible to work with. Is there a chance to update the SDL2 libraries for this port and fix the controller issues? I was also using a wireless Xbox One controller connected via Bluetooth with the x64 build when I discovered this problem.

**Comment by KScl** [comment]
Belatedly closing as invalid. Replacing the .dll that OT2K uses isn't going to suddenly make it aware of any changes that have been made in that .dll due to the version change, and in fact is prone to causing problems just like this.

Using a later version of SDL2 is only planned if mainline does so, and currently I'm not sure if it does.

**Comment by ViperAcidZX** [comment]
I just checked the original OpenTyrian port's latest release and it is using SDL2 v2.26.0.0 as of the November 14, 2022 build.
