### ISSUE TITLE
Incorrect palette and sprites in some things

### ISSUE THREAD

**Issue by TsukiZero** [KScl/opentyrian2000#8]
Carrot Ship in the shop uses the wrong palette and no transparency, Zica Flamethrower uses a glitched projectile sprite.

**Comment by KScl** [comment]
It's currently December and Xmas mode is active, and Tyrian 2000's Xmas data files contain major errors. That's not really OpenTyrian2000's fault, it's doing everything correct with what it's given.

(For the curious, the reason projectiles look glitched is because in the T2K Xmas data files, the second player shot sprite sheet is a copy of the first. And yes, the SuperCarrot just ... lacks transparency entirely, for whatever reason.)

**Comment by TsukiZero** [comment]
I doubt it is simply due to Xmas mode, but I'd need to find Zica Flamethrower again and not quite in the mood for it yet.
