### ISSUE TITLE
Bug on Scaling Mode

### ISSUE THREAD

**Issue by WilliamWeberBerrutti** [KScl/opentyrian2000#9]
When using "Scaling Mode: Fit to 8:5", Player 1 (or Player 2 in 2-player mode) moves slowly to the left permanently.

**Comment by KScl** [comment]
Relevant issue/commit in mainline: opentyrian#34, 0206a17

This should get coincidentally fixed when I have the opportunity to rebase all the changes mainline did in the past year or so. I haven't had the time lately (and won't for this month due to an impending move), but I'll keep it in mind when everything settles down.

**Comment by KScl** [comment]
Confirmed fixed by 132e8b4.
